# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf9aa56a4961200a9394ce605803c30c667f9970854a90f71c12e204fb1055a1bdf3218943f882a62e092ec13e533128d72be74dd8500da0ef54045ba18dfc6

test:
  secret_key_base: dc60c342708ceda54bb16f5f446ebe5f4f405de2b276257f3841f56737f911ffde9e6cb63928b6f62a1b7a40aec29f0ab98b306c4c8796317f42d5bb4236ecb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
